config/routes.rb
Patienthub::Application.routes.draw do

  resources :diagnoses

  get '/', controller: 'conditions', action: 'index'
  get '/login', controller: 'sessions', action: 'new'
  post '/sessions', controller: 'sessions', action: 'create'
  get "/logout", controller: 'sessions', action: 'destroy'

  get '/home', controller: 'home_page', action: 'show', as: "home_page"

  get '/conditions/new', controller: 'conditions', action: 'new', as: "new_condition"
  post "/conditions", controller: 'conditions', action: 'create'
  get '/conditions', controller: 'conditions', action: 'index', as: "conditions"
  get '/conditions/:condition_id', controller: 'conditions', action: 'show', as: "condition"
  get '/conditions/:condition_id/edit', controller: 'conditions', action: 'edit', as: "edit_condition"
  put '/conditions/:condition_id', controller: 'conditions', action: 'update'
  delete '/conditions/:condition_id', controller: 'conditions', action: 'destroy'
  post "/conditions/search", controller: 'conditions', action: 'filter'

 get '/users/new', controller: 'users', action: 'new', as: "new_user"
 post "/users", controller: 'users', action: 'create'
 get "/users", controller: 'users', action: 'index', as: "users"
 get '/users/:user_id', controller: 'users', action: 'show', as: "user"
 get "/users/:user_id/edit", controller: 'users', action: 'edit', as: "edit_user"
 put '/users/:user_id', controller: 'users', action: 'update'
 delete '/users/:user_id', controller: 'users', action: 'destroy'
 post "/users/search", controller: 'users', action: 'filter'

 get '/treatments/new', controller: 'treatments', action: 'new', as: "new_treatment"
 post "/treatments", controller: 'treatments', action: 'create'
 get "/treatments", controller: 'treatments', action: 'index', as: "treatments"
 get '/treatments/:treatment_id', controller: 'treatments', action: 'show', as: "treatment"
 get "/treatments/:treatment_id/edit", controller: 'treatments', action: 'edit', as: "edit_treatment"
 put '/treatments/:treatment_id', controller: 'treatments', action: 'update'
 delete '/treatments/:treatment_id', controller: 'treatments', action: 'destroy'
 post "/treatments/search", controller: 'treatments', action: 'filter'

end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
  attr_accessible :treatment_name

  belongs_to :treatment_category
  has_many :diagnoses
  has_many :conditions, through: :diagnoses
  has_many :users, through: :diagnoses

  validates :treatment_name, presence: true

end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController

 def destroy
    m = Treatment.find_by_id(params["treatment_id"])
    m.destroy
    redirect_to "/treatments"
  end

  def edit
    @treatment = Treatment.find_by_id(params["treatment_id"])
  end

  def filter
    search_term = params["term"]
    @treatments = Treatment.where("treatment_name LIKE ? OR treatment_id = ?", "%#{search_term}%", search_term)
    render 'index'
  end

  def update
    @treatment = Treatment.find_by_id(params["treatment_id"])
    @treatment.treatment_name = params[:treatment_name]
    @treatment.treatment_category_id = params[:treatment_category_id]
    @treatment.save
    redirect_to "/treatments"
  end

  def create
    @treatment = Treatment.new
    @treatment.treatment_name = params[:treatment_name]
    @treatment.treatment_category_id = params[:treatment_category_id]
    @treatment.save
    redirect_to "/treatments"
  end

  def index
    @treatments = Treatment.all
  end

  def show
    @treatment = Treatment.find_by_id(params["treatment_id"])
  end

  def new
  @treatment = Treatment.new
  end

end

app/views/treatments/edit.html.erb
<h1>Editing Treatment #<%= @treatment.id %></h1>


<%= form_tag(treatment_url(@treatment), method: 'put') do %>

  <div>
    <%= label_tag :treatment_name %><br />
    <%= text_field_tag :treatment_name, @user.treatment_name %>
  </div>

  <div>
    <%= label_tag :treatment_id %><br />
    <%= text_field_tag :treatment_id, @user.treatment_id %>
  </div>

  <div>
    <%= label_tag :treatment_category_id %><br />
    <%= text_field_tag :treatment_category_id, @user.treatment_category_id %>
  </div>


  <div>
    <%= submit_tag "Update Treatment" %>
  </div>

<% end %>

app/views/treatments/index.html.erb
<h2>Treatments</h2>

<%= form_tag '/treatments/search' do %>
<%= text_field_tag :term, "", placeholder: 'Search...' %><% end %>

<p><%= link_to 'Add a New Treatment', new_treatment_url %></p>

<table class = "table table-striped">
  <thead>
    <tr>
      <th>Treatment category</th>
      <th>Treatment</th>
      <th>Users affected </th>
      <th>Actions </th>
    </tr>
  </thead>

 <tbody>
  <% @treatments.each do |treatment| %>
    <tr>
      <td><%= treatment.treatment_category.treatment_category_name %></td>
      <td><%= link_to treatment.treatment_name.truncate(40), "/treatments/#{treatment.id}" %></td>
      <td><%=   %></td>
      <td><%= link_to 'Edit', edit_treatment_url(treatment) %> |
      <%= link_to 'Delete', treatment_url(treatment), method: 'delete', data: { confirm: "Do you really want to delete this treatment?" } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/treatments/new.html.erb
<h2>Add a treatment to the directory</h2>


<%= form_tag(treatments_url, method: 'post') do %>


  <div>
    <%= label_tag :treatment_name %><br />
    <%= text_field_tag :treatment_name %>
  </div>

  <div>
    <%= label_tag :treatment_category_name %><br />
    <%= text_field_tag :treatment_category_name %>
  </div>

  <div>
    <%= submit_tag "Create Treatment" %>
  </div>
<% end %>

app/views/treatments/show.html.erb
<h2><%= @treatment.treatment_name %></h2>

<dl class="dl-horizontal">
<dt>Treatment category ID:</dt> <dd><%= @treatment.treatment_category.treatment_category_name %></dd>
<dt>Users:</dt> <dd><%= @treatment.diagnoses.count %></dd>
</dl>