config/routes.rb
Patienthub::Application.routes.draw do

  resources :diagnoses

  get '/', controller: 'conditions', action: 'index'
  get '/login', controller: 'sessions', action: 'new'
  post '/sessions', controller: 'sessions', action: 'create'
  get "/logout", controller: 'sessions', action: 'destroy'

  get '/home', controller: 'home_page', action: 'show', as: "home_page"

  get '/conditions/new', controller: 'conditions', action: 'new', as: "new_condition"
  post "/conditions", controller: 'conditions', action: 'create'
  get '/conditions', controller: 'conditions', action: 'index', as: "conditions"
  get '/conditions/:condition_id', controller: 'conditions', action: 'show', as: "condition"
  get '/conditions/:condition_id/edit', controller: 'conditions', action: 'edit', as: "edit_condition"
  put '/conditions/:condition_id', controller: 'conditions', action: 'update'
  delete '/conditions/:condition_id', controller: 'conditions', action: 'destroy'
  post "/conditions/search", controller: 'conditions', action: 'filter'

 get '/users/new', controller: 'users', action: 'new', as: "new_user"
 post "/users", controller: 'users', action: 'create'
 get "/users", controller: 'users', action: 'index', as: "users"
 get '/users/:user_id', controller: 'users', action: 'show', as: "user"
 get "/users/:user_id/edit", controller: 'users', action: 'edit', as: "edit_user"
 put '/users/:user_id', controller: 'users', action: 'update'
 delete '/users/:user_id', controller: 'users', action: 'destroy'
 post "/users/search", controller: 'users', action: 'filter'

 get '/treatments/new', controller: 'treatments', action: 'new', as: "new_treatment"
 post "/treatments", controller: 'treatments', action: 'create'
 get "/treatments", controller: 'treatments', action: 'index', as: "treatments"
 get '/treatments/:treatment_id', controller: 'treatments', action: 'show', as: "treatment"
 get "/treatments/:treatment_id/edit", controller: 'treatments', action: 'edit', as: "edit_treatment"
 put '/treatments/:treatment_id', controller: 'treatments', action: 'update'
 delete '/treatments/:treatment_id', controller: 'treatments', action: 'destroy'
 post "/treatments/search", controller: 'treatments', action: 'filter'

end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController

  def destroy
    m = Diagnosis.find_by_id(params[:id])
    m.destroy
    redirect_to "/diagnoses"
  end

  def edit
    @diagnosis = Diagnosis.find_by_id(params[:id])
  end

  def filter
    search_term = params["term"]
    @diagnoses = Diagnosis.where("treatment_name LIKE ? OR condition_name = ?", "%#{search_term}%", search_term)
    render 'index'
  end

  def update
    @diagnosis = Diagnosis.find_by_id(params[:id])
    @diagnosis.treatment_name = params[:treatment_name]
    @diagnosis.condition_name = params[:condition_name]
    @diagnosis.user_name = params[:user_name]
    @diagnosis.save
    redirect_to "/diagnoses"
  end

  def create
    @diagnosis = Diagnosis.new
    @diagnosis.treatment_name = params[:treatment_name]
    @diagnosis.condition_name = params[:condition_name]
    @diagnosis.user_name = params[:user_name]
    @diagnosis.save
    redirect_to "/diagnoses"
  end

  def index
    @diagnoses = Diagnosis.all
  end

  def show
    @diagnosis = Diagnosis.find_by_id(params[:condition_id])
  end

  def new
  @diagnosis = Diagnosis.new
  end

end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/views/diagnoses/_form.html.erb
<%= form_for(@diagnosis) do |f| %>
  <% if @diagnosis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diagnosis.errors.count, "error") %> prohibited this diagnosis from being saved:</h2>

      <ul>
      <% @diagnosis.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :treatment_id %><br />
    <%= f.number_field :treatment_id %>
  </div>
  <div class="field">
    <%= f.label :condition_id %><br />
    <%= f.number_field :condition_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diagnoses/edit.html.erb
<h1>Editing diagnosis</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagnosis %> |
<%= link_to 'Back', diagnoses_path %>

app/views/diagnoses/index.html.erb
<h2>Diagnoses</h2>

<%= link_to 'New Diagnosis', new_diagnosis_path %>

<table class = "table table-striped">
  <thead>
  <tr>
    <th>User</th>
    <th>Treatment</th>
    <th>Condition</th>
    <th>Actions</th>
  </tr>
    </thead>
  <tbody>
<% @diagnoses.each do |diagnosis| %>
  <tr>
    <td><%= diagnosis.user_name %></td>
    <td><%= diagnosis.treatment_name %></td>
    <td><%= diagnosis.condition_name %></td>
    <td><%= link_to 'Show', diagnosis %> |
    <%= link_to 'Edit', edit_diagnosis_path(diagnosis) %> |
    <%= link_to 'Destroy', diagnosis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/diagnoses/new.html.erb
<h1>New diagnosis</h1>

<%= render 'form' %>

<%= link_to 'Back', diagnoses_path %>

app/views/diagnoses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @diagnosis.user_name %>
</p>

<p>
  <b>Treatment:</b>
  <%= @diagnosis.treatment_name %>
</p>

<p>
  <b>Condition:</b>
  <%= @diagnosis.condition_name %>
</p>


<%= link_to 'Edit', edit_diagnosis_path(@diagnosis) %> |
<%= link_to 'Back', diagnoses_path %>