config/routes.rb
Patienthub::Application.routes.draw do

  resources :diagnoses

  get '/', controller: 'conditions', action: 'index'
  get '/login', controller: 'sessions', action: 'new'
  post '/sessions', controller: 'sessions', action: 'create'
  get "/logout", controller: 'sessions', action: 'destroy'

  get '/home', controller: 'home_page', action: 'show', as: "home_page"

  get '/conditions/new', controller: 'conditions', action: 'new', as: "new_condition"
  post "/conditions", controller: 'conditions', action: 'create'
  get '/conditions', controller: 'conditions', action: 'index', as: "conditions"
  get '/conditions/:condition_id', controller: 'conditions', action: 'show', as: "condition"
  get '/conditions/:condition_id/edit', controller: 'conditions', action: 'edit', as: "edit_condition"
  put '/conditions/:condition_id', controller: 'conditions', action: 'update'
  delete '/conditions/:condition_id', controller: 'conditions', action: 'destroy'
  post "/conditions/search", controller: 'conditions', action: 'filter'

 get '/users/new', controller: 'users', action: 'new', as: "new_user"
 post "/users", controller: 'users', action: 'create'
 get "/users", controller: 'users', action: 'index', as: "users"
 get '/users/:user_id', controller: 'users', action: 'show', as: "user"
 get "/users/:user_id/edit", controller: 'users', action: 'edit', as: "edit_user"
 put '/users/:user_id', controller: 'users', action: 'update'
 delete '/users/:user_id', controller: 'users', action: 'destroy'
 post "/users/search", controller: 'users', action: 'filter'

 get '/treatments/new', controller: 'treatments', action: 'new', as: "new_treatment"
 post "/treatments", controller: 'treatments', action: 'create'
 get "/treatments", controller: 'treatments', action: 'index', as: "treatments"
 get '/treatments/:treatment_id', controller: 'treatments', action: 'show', as: "treatment"
 get "/treatments/:treatment_id/edit", controller: 'treatments', action: 'edit', as: "edit_treatment"
 put '/treatments/:treatment_id', controller: 'treatments', action: 'update'
 delete '/treatments/:treatment_id', controller: 'treatments', action: 'destroy'
 post "/treatments/search", controller: 'treatments', action: 'filter'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :comments, :condition_id, :first_name, :last_name, :password_digest, :treatment_id, :user_id, :user_name, :user_type, :zip_code, :email

  user_type =["Expert", "User"]

  has_secure_password

  has_many :diagnoses
  has_many :conditions, through: :diagnoses
  has_many :treatments, through: :diagnoses

  validates :user_name, presence: true, uniqueness: true
  validates :email, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :zip_code, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 99950}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def destroy
    @user = User.find_by_id(params[:user_id])
    @user.destroy
    redirect_to "/users"
  end

  def edit
    @user = User.find_by_id(params[:user_id])
  end

  def filter
    search_term = params["term"]
    @users = User.where("user_name LIKE ? OR first_name LIKE ?", "%#{search_term}%", search_term)
    render 'index'
  end

  def update
    @user = User.find_by_id(params[:user_id])
    @user.user_name = params[:user_name]
    @user.password = params[:password]
    @user.email = params[:email]
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.user_type = params[:user_type]
    @user.condition_id = params[:condition_id]
    @user.zip_code = params[:zip_code]
    @user.treatment_id = params[:treatment_id]
    @user.comments = params[:comments]
    @user.save
    redirect_to "/users"
  end

  def create
    @user = User.new
    @user.user_name = params[:user_name]
    @user.password = params[:password]
    @user.email = params[:email]
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.user_type = params[:user_type]
    @user.condition_id = params[:condition_id]
    @user.zip_code = params[:zip_code]
    @user.treatment_id = params[:treatment_id]
    @user.comments = params[:comments]
    @user.save
    redirect_to "/users"
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params["user_id"])
  end

  def new
  @user = User.new
  end

end

app/views/users/edit.html.erb
<h2>Editing User #<%= @user.user_name %></h2>


<%= form_tag(user_url(@user), method: 'put') do %>

  <div>
    <%= label_tag :user_name %><br />
    <%= text_field_tag :user_name, @user.user_name %>
  </div>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, @user.email %>
  </div>

    <div>
    <%= label_tag :password %><br />
    <%= password_field_tag :password, @user.password %>
  </div>

  <div>
    <%= label_tag :first_name %><br />
    <%= text_field_tag :first_name, @user.first_name %>
  </div>

  <div>
    <%= label_tag :last_name %><br />
    <%= text_field_tag :last_name, @user.last_name %>
  </div>

    <div>
    <%= label_tag :user_type %><br />
    <%= text_field_tag :user_type, @user.user_type %>
  </div>

    <div>
    <%= label_tag :zip_code %><br />
    <%= text_field_tag :zip_code, @user.zip_code %>
  </div>

  <div>
    <%= label_tag :condition_id %><br />
    <%= text_field_tag :condition_id, @user.condition_id %>
  </div>

  <div>
    <%= label_tag :treatment_id %><br />
    <%= text_field_tag :treatment_id, @user.treatment_id %>
  </div>

    <div>
    <%= label_tag :comments %><br />
    <%= text_field_tag :comments, @user.comments %>
  </div>

  <div>
    <%= submit_tag "Update User" %>
  </div>

<% end %>

app/views/users/index.html.erb
<h2>Users</h2>

<%= form_tag '/users/search' do %>
<%= text_field_tag :term, "", placeholder: 'Search...' %><% end %>

<p><%= link_to 'Add a New User', new_user_url %></p>

<table class = "table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Zip code</th>
      <th>User type</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.user_name.truncate(40), "/users/#{user.id}" %></td>
      <td><%= user.zip_code %></td>
      <td><%= user.user_type %></td>
      <td><%= user.email.truncate(25) %></td>
      <td><%= link_to 'Edit', edit_user_url(user) %> |
      <%= link_to 'Delete', user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h2>Create an account</h2>


<%= form_tag(users_url, method: 'post') do %>


  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>

  <div>
    <%= label_tag :user_name %><br />
    <%= text_field_tag :user_name %>
  </div>

  <div>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>

  <div>
    <%= label_tag :first_name %><br />
    <%= text_field_tag :first_name %>
  </div>

  <div>
    <%= label_tag :last_name %><br />
    <%= text_field_tag :last_name %>
  </div>


  <div>
    <%= label_tag :zip_code %><br />
    <%= text_field_tag :zip_code %>
  </div>

  <div>
    <%= label_tag :user_type  %><br />
    <%= text_field_tag :user_type %> "Expert" or "User"
  </div>

    <div>
    <%= label_tag :comments %><br />
    <%= text_field_tag :comments %>
  </div>

  <div>
    <%= submit_tag "Create User" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h2>User profile: <%= @user.user_name %></h2>

<dl class="dl-horizontal">
<dt>First Name:</dt> <dd><%= @user.first_name %></dd>
<dt>Last Name:</dt> <dd><%= @user.last_name %></dd>
<dt>User Type:</dt> <dd><%= @user.user_type %></dd>
<dt>Zip Code:</dt> <dd><%= @user.zip_code %></dd>
<dt>Condition ID:</dt> <dd><%= @user.condition_id %></dd>
<dt>Treatments:</dt> <dd><%= @user.treatment_id %></dd>
<dt>Comments:</dt> <dd><%= @user.comments %></dd>
</dl>